<?php

$title = 'Add new Book';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title);?></h1>
<?php

if (!empty($form)) {
    $form->setAttribute('action', $this->url('tutorial', [
        'action' => 'add',
    ]));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('author')) . '<br>';
    echo $this->formRow($form->get('title')) . '<br>';
    echo $this->formRow($form->get('imagepath')) . '<br>';
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag($form);
}
