<?php

$title = 'Delete an employee record';
$this->headTitle($title);

?>
            <h1><?= $this->escapeHtml($title); ?></h1>
            <p>'<?= $this->escapeHtml($employee->emp_name); ?>' by '<?= $this->escapeHtml(
                    $employee->emp_job); ?>'</p>
            <form accept="<?= $this->url('employee', [
                    'action' => 'delete', 'id' => $this->id]); ?>" method="post">
                <input type="hidden" name="id" value="<?= (int)$employee->id; ?>">
                <input type="submit" name="del" value="Yes">
                <input type="submit" name="del" value="No">
            </form>
